name: GitHub Actions Demo
run-name: ${{ github.actor }}
on: [push]
jobs:
  Explore:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello, world!"
      - name: Check out the code
        uses: actions/checkout@v4
